### PR TITLE
handle multiple-valued results in `report`

### PR DESCRIPTION
**Pull request by mbutterick**
With one value, works the same as before. With multiple values, prints `(values v ...)`

### CODE REVIEW

**Comment by AlexKnauth** [comment]
Thanks, I definitely want something like this. The only thing I'm worried about, however, is how it might  interact with Typed Racket. I'm trying it out now...

**Comment by AlexKnauth** [comment]
Programs using `report` in typed racket currently succeed, but break with this pull request:
```racket
#lang typed/racket
(require debug/report)
(define x 5)
(report x)
```

I might have to create a typed version of this library just so things like this can still work in typed racket.

**Comment by AlexKnauth** [comment]
I just added the [`typed`](https://github.com/AlexKnauth/debug/tree/typed) branch to experiment with this. With that branch, typed racket programs can use `typed/debug/report` instead. 

Helper functions like `stringify-results` can go in `debug/report/helpers`, with type annotations in `typed/debug/report/helpers`. Then typed racket programs that use `typed/debug/report` will work.

This will break typed racket programs that don't switch to `typed/debug/report`, but I think that's unavoidable if we want nice things like this.

**Comment by AlexKnauth** [comment]
I've pushed a modification of this on the [`typed-mbutterick-patch-1`](https://github.com/AlexKnauth/debug/tree/typed-mbutterick-patch-1) branch, but even with an annotation for `stringify-results` it's still failing on the `apply values`:
```
. Type Checker: Bad arguments to function in `apply':
Domains: a b ... b
         
Arguments:  (Listof Positive-Byte)
 in: (report x)
```

We need a way to "pass through" the values in a way that typed racket will understand.

**Comment by AlexKnauth** [comment]
The [`typed-mbutterick-patch-1`](https://github.com/AlexKnauth/debug/tree/typed-mbutterick-patch-1) is now in a state where "it works." I had to give (unsafe) annotations to four different helper functions for typed racket to be happy. Would you like to look at that branch (and maybe propose some alternative ideas) before I look at merging it?

**Comment by mbutterick** [comment]
I defer to your expert judgment. About TR, I know nothing.

**Comment by AlexKnauth** [comment]
Thanks!

**Pull request merged**
